name: Auto Merge Dependencies
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  check_suite:
    types: [ completed ]
  status: { }

permissions:
  contents: write
  pull-requests: write
