name: Dependabot Auto-merge
on: pull_request_target

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Check if PR is mergeable
        id: mergeable
        run: |
          PR_DATA=$(gh api /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }})
          MERGEABLE=$(echo $PR_DATA | jq -r .mergeable)
          MERGEABLE_STATE=$(echo $PR_DATA | jq -r .mergeable_state)
          echo "mergeable=$MERGEABLE" >> $GITHUB_OUTPUT
          echo "mergeable_state=$MERGEABLE_STATE" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge for Dependabot PRs
        if: |
          steps.mergeable.outputs.mergeable == 'true' &&
          (
            (steps.metadata.outputs.update-type == 'version-update:semver-patch') ||
            (steps.metadata.outputs.update-type == 'version-update:semver-minor') ||
            (contains(steps.metadata.outputs.dependency-names, 'pestphp') && steps.metadata.outputs.update-type == 'version-update:semver-major') ||
            (contains(steps.metadata.outputs.dependency-names, 'phpunit') && steps.metadata.outputs.update-type == 'version-update:semver-major') ||
            (contains(steps.metadata.outputs.dependency-names, 'phpstan') && steps.metadata.outputs.update-type == 'version-update:semver-major')
          )
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on major updates
        if: steps.metadata.outputs.update-type == 'version-update:semver-major'
        run: |
          gh pr comment "$PR_URL" --body "⚠️ This is a major version update. Manual review recommended."
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on unmergeable PR
        if: steps.mergeable.outputs.mergeable != 'true'
        run: |
          gh pr comment "$PR_URL" --body "⚠️ This PR is not automatically mergeable. State: ${{ steps.mergeable.outputs.mergeable_state }}"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
