name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.2, 8.3, 8.4 ]
        laravel: [ 11.* ]
        experimental: [ false ]
        include:
          - php: 8.4
            laravel: 11.*
            experimental: true
          - php: 8.2
            laravel: 12.*
            experimental: true
          - php: 8.3
            laravel: 12.*
            experimental: true
          - php: 8.4
            laravel: 12.*
            experimental: true

    name: P${{ matrix.php }} - L${{ matrix.laravel }}
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          coverage: pcov

      - name: Install dependencies
        run: |
          if [[ ${{ matrix.laravel }} == "12.*" ]]; then
            composer config platform.php ${{ matrix.php }}
            composer remove --dev larastan/larastan --no-update
            composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
            composer update --prefer-stable --prefer-dist --no-interaction --no-progress
          else
            composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
            composer update --prefer-stable --prefer-dist --no-interaction --no-progress
          fi

      - name: Check coding style
        run: vendor/bin/pint --test

      - name: Execute tests
        if: ${{ matrix.laravel != '12.*' }}
        run: vendor/bin/pest --coverage

      - name: Execute tests (Laravel 12)
        if: ${{ matrix.laravel == '12.*' }}
        run: |
          # Skip phpstan since we removed larastan for Laravel 12
          vendor/bin/pest --coverage --skip-coverage

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Run Pint
        run: vendor/bin/pint

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fix styling
          branch: ${{ github.head_ref }}
